name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  NODE_VERSION: 24

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - name: Windows
            os: windows-latest

          - name: Linux
            os: ubuntu-latest

          - name: macOS
            os: macos-14

        # Exclude windows and macos from being built on feature branches
        run-all:
          - ${{ github.ref == 'refs/heads/master' || contains(github.event.pull_request.body, '[ci-all]') || github.event.pull_request.user.login == 'depfu[bot]' }}
        exclude:
          - run-all: false
            runner:
              name: Windows
          - run-all: false
            runner:
              name: macOS

    runs-on: ${{ matrix.runner.os }}
    timeout-minutes: 30

    name: ${{ matrix.runner.name }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint
        # Only lint on linux to avoid \r\n line ending errors
        if: matrix.runner.os == 'ubuntu-latest'

      - name: Test
        run: pnpm run test

      # - name: Install Playwright Browsers
      # # #   run: npx playwright install --with-deps

      # - name: Run Playwright tests
      #   run: npm run test:ui

  notify:
    if: ${{ always() && github.ref == 'refs/heads/master' && needs.tests.result == 'failure' }}
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: 'The [most recent ${{ github.workflow }} workflow](<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>) on the `master` branch has failed.'
